name: Appium-WDIO-Cypress Job

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'dev'
      
      #Workaround while understanding deployment_status
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'

jobs:
  cypress-github-pipeline:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.12
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # TO DO - Debug which step takes less time between this one and "Create AVD and generate snapshot for caching"
      # - name: Create AVD
      #   run: |
      #     sdkmanager "system-images;android-23;google_apis;x86_64"
      #     yes | sdkmanager --licenses
      #     avdmanager create avd -n DemoAVD -k "system-images;android-33;google_apis;x86_64" -d pixel
      
      - name: Create AVD and generate snapshot for caching
        uses: reactivecircus/android-emulator-runner@v2
        with:
          avd-name: DemoAVD
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot"

      - name: Download AVD APK
        run: |
          mkdir wdio/apk
          cd cypress/config/cucumber_json
          curl https://github.com/appium/appium/blob/master/packages/appium/sample-code/apps/ApiDemos-debug.apk -o ApiDemos-debug.apk
          
      # Setting environment
      - name: Set Up Environment
        run: |
          echo "TEST_ENVIRONMENT=${{ github.event.inputs.deployment == 'yes' && 'dev' || github.event.inputs.env}}" >> $GITHUB_ENV
          mkdir cypress/config/cucumber_json
          echo "${{ github.workspace }}/cypress/config/cucumber_json" >> $GITHUB_PATH
          cd cypress/config/cucumber_json
          curl https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -o cucumber-json-formatter
          chmod +x cucumber-json-formatter

      #NPM Installation and Cypress execution
      - name: Cypress Execution
        uses: cypress-io/github-action@v4
        with:
          # ci-build-id: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          # tag: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          # record: true
          browser: electron
          headed: false
          install: true
        env:
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
          CYPRESS_TEST_TRIGGER: ${{github.event_name}}
          CYPRESS_envKey: ${{env.TEST_ENVIRONMENT}}
          CYPRESS_TAGS: "not @skip"
